## CHANGE this to the name of your plugin.
name: FluffyMachines

authors: [NCBPFluffyBear, iYanZ]

description: A fun addon

main: io.ncbpfluffybear.fluffymachines.FluffyMachines

depend: [Slimefun]
softdepend: [mcMMO, NoCheatPlus]

version: ${project.version}

api-version: "1.21.4"

commands:
  fluffymachines:
    description: FluffyMachines Command
    usage: /<command>
    aliases: [fm]

permissions:
  fluffymachines.admin:
    description: Allows you to use FluffyMachines admin commands